CREATE TABLE IF NOT EXISTS USERS
(
    ID      INTEGER    PRIMARY KEY AUTOINCREMENT NOT NULL,
    NICKNAME    TEXT       NOT NULL,
    PASSWORD    TEXT       NOT NULL,
    EMAIL       TEXT       NOT NULL
);